"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { activePage, getOriginalMap, originalStart, passable, tileAt, triggerEvent, type WorldPosition } from "../game-core/original-world";
import { applySceneResolution, resolveSceneEvent, type SceneActorState } from "../game-core/scene-event";
import { selectSceneEvent } from "../game-core/rmxp-events";
import { attemptJoin, buyGood, npcOptionLabel, npcOptions, npcRecord, npcStatus, shopGoods, studyOnce, studyOptions, type NpcOption } from "../game-core/npc-system";
import { battleRound, beginOriginalBattle, endSpar, type OriginalBattle } from "../game-core/original-battle";
import { bagEntries, derivedStats, maxFood, maxWater, activateEntry, type BagEntry } from "../game-core/inventory-system";
import { equipSkill, learnedSkills, toggleParry } from "../game-core/skill-system";
import "./world.css";
import "./choice.css";
import "./battle.css";
import "./menu.css";

const W=640,H=480,T=32;
type WorldSave={format:"rmxp-hero-original-world-save";version:1;savedAt:string;position:WorldPosition;flags:Record<string,boolean>;variables:Record<string,number>;actor:SceneActorState};
const newActor=():SceneActorState=>({inventory:{},gold:100,hp:100,maxHp:100,fp:0,maxFp:0,food:100,water:100,exp:0,potential:100,morals:128,tanId:0,teacherId:0,classId:0,gender:0,face:20,maxMp:0,age:14,baseBon:20,baseInt:20,baseAgi:20,baseStr:20,bon:20,int:20,agi:20,str:20,luck:20,skills:{},weaponId:0,armorIds:[],skillUse:[0,0,0,0,0,0],fpPlus:0});
const fresh=():WorldSave=>({format:"rmxp-hero-original-world-save",version:1,savedAt:new Date().toISOString(),position:{...originalStart},flags:{},variables:{},actor:newActor()});
const normalize=(value:WorldSave):WorldSave=>({...value,actor:{...newActor(),...(value.actor||{}),skills:value.actor?.skills||{},inventory:value.actor?.inventory||{}},flags:value.flags||{},variables:value.variables||{}});
const loadSave=():WorldSave=>{if(typeof window==="undefined")return fresh();try{const raw=localStorage.getItem("rmxp-original-world-v1");return raw?normalize(JSON.parse(raw)):fresh();}catch{return fresh();}};

export default function OriginalWorld(){
 const [state,setState]=useState<WorldSave>(loadSave),[notice,setNotice]=useState("原版地图数据已载入"),[eventText,setEventText]=useState("");
 const [npcMenu,setNpcMenu]=useState<{id:number;index:number}|null>(null),[shop,setShop]=useState<{id:number;index:number}|null>(null),[study,setStudy]=useState<{id:number;index:number}|null>(null);
 const [battle,setBattle]=useState<OriginalBattle|null>(null);
 const [menu,setMenu]=useState<{tab:number;index:number}|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null), file=useRef<HTMLInputElement>(null), stateRef=useRef<WorldSave>(state), keys=useRef(new Set<string>()),held=useRef<Record<string,number>>({});
 const sync=useCallback((next:WorldSave)=>{stateRef.current=next;setState(structuredClone(next));},[]);
 const save=useCallback(()=>{const next={...stateRef.current,savedAt:new Date().toISOString()};sync(next);localStorage.setItem("rmxp-original-world-v1",JSON.stringify(next));setNotice("原版世界进度已保存");},[sync]);
 const runAt=useCallback((x:number,y:number,automatic=false)=>{const s=stateRef.current,map=getOriginalMap(s.position.mapId),hook=triggerEvent(map,x,y);if(!hook)return false;const {result,event,page}=hook;if(result.transfer){const next=structuredClone(s);next.position={mapId:result.transfer.mapId,x:result.transfer.x,y:result.transfer.y,direction:result.transfer.direction||s.position.direction};sync(next);setNotice(`抵达 · ${getOriginalMap(next.position.mapId).name}`);return true;}const sceneCall=selectSceneEvent(result.source,{inventory:s.actor.inventory,tanId:s.actor.tanId,freeWork:s.variables.freeWork||0,canGetItem:true,canGetCaihua:true});if(sceneCall&&!automatic){if(sceneCall.type===0&&sceneCall.id!==undefined){setNpcMenu({id:sceneCall.id,index:0});return true;}const next=structuredClone(s),resolution=resolveSceneEvent(sceneCall,next.actor,event.id+s.position.mapId);applySceneResolution(next.actor,resolution);if(resolution.transfer)next.position={...resolution.transfer,direction:next.position.direction};sync(next);setEventText(`${event.name||"地图事件"}\n${resolution.lines.join("\n")}`);setNotice(`原版事件 · ${resolution.tag}`);return true;}if(!automatic&&result.source&&!sceneCall){setNotice("尚未满足该事件的原版触发条件");return true;}return page.trigger>0;},[sync]);
 const move=useCallback((dx:number,dy:number)=>{if(eventText||npcMenu||shop||study||battle||menu)return;const s=structuredClone(stateRef.current),map=getOriginalMap(s.position.mapId);const direction=dx<0?4:dx>0?6:dy<0?8:2,nx=s.position.x+dx,ny=s.position.y+dy;s.position.direction=direction;if(!passable(map,nx,ny,direction)){sync(s);return;}const blocking=map.events.find(e=>e.x===nx&&e.y===ny&&String(activePage(e).graphic?.character_name||"")&&!activePage(e).through);if(!blocking){s.position.x=nx;s.position.y=ny;sync(s);runAt(nx,ny,true);}else sync(s);},[battle,eventText,menu,npcMenu,runAt,shop,study,sync]);
 const interact=useCallback(()=>{const p=stateRef.current.position,d=p.direction===2?[0,1]:p.direction===4?[-1,0]:p.direction===6?[1,0]:[0,-1];if(!runAt(p.x+d[0],p.y+d[1]))setNotice("这里没有可以触发的事件");},[runAt]);
 const chooseNpc=useCallback((id:number,option:NpcOption)=>{const next=structuredClone(stateRef.current);if(option==="talk"){const r=resolveSceneEvent({type:0,id},next.actor,id+next.position.mapId);setEventText(`${npcRecord(id).name}\n${r.lines.join("\n")}`);}else if(option==="status")setEventText(npcStatus(id).join("\n"));else if(option==="battle")setBattle(beginOriginalBattle(id,id+next.position.mapId));else if(option==="trade")setShop({id,index:0});else if(option==="join"){const r=attemptJoin(id,next.actor);sync(next);setEventText(`${npcRecord(id).name}\n${r.text}`);}else setStudy({id,index:0});setNpcMenu(null);},[sync]);
 const fight=useCallback(()=>{if(!battle||battle.finished)return;const next=structuredClone(stateRef.current),round=battleRound(battle,next.actor);sync(next);setBattle(round);},[battle,sync]);
 const leaveBattle=useCallback(()=>{if(!battle)return;const next=structuredClone(stateRef.current);endSpar(next.actor,battle);sync(next);setBattle(null);setNotice(battle.finished==="win"?"切磋得胜":battle.finished==="lose"?"切磋结束，已恢复少量气血":"你退出了切磋");},[battle,sync]);
 const activateBagEntry=useCallback((entry?:BagEntry)=>{if(!entry)return;const next=structuredClone(stateRef.current),result=activateEntry(next.actor,entry);sync(next);setNotice(result.text);const count=bagEntries(next.actor).length;setMenu(current=>current?{...current,index:Math.min(current.index,Math.max(0,count-1))}:current);},[sync]);
 const activateSkill=useCallback((id?:number,parry=false)=>{if(!id)return;const next=structuredClone(stateRef.current),result=parry?toggleParry(next.actor,id):equipSkill(next.actor,id);sync(next);setNotice(result.text);},[sync]);
 const buyAt=useCallback((id:number,index:number)=>{const good=shopGoods(id)[index];if(!good)return;const next=structuredClone(stateRef.current),r=buyGood(next.actor,good);sync(next);setNotice(r.text);},[sync]);
 const buySelected=useCallback(()=>{if(shop)buyAt(shop.id,shop.index);},[buyAt,shop]);
 const studyAt=useCallback((id:number,index:number)=>{const item=studyOptions(id)[index];if(!item)return;const next=structuredClone(stateRef.current),r=studyOnce(next.actor,item.id,item.maxLevel);sync(next);setNotice(r.text);},[sync]);
 const studySelected=useCallback(()=>{if(study)studyAt(study.id,study.index);},[study,studyAt]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright"," ","tab"].includes(k))e.preventDefault();keys.current.add(k);const confirm=["z","enter"," "].includes(k),cancel=["x","escape"].includes(k);if(battle){if(confirm)fight();else if(cancel)leaveBattle();return;}if(menu){const entries=bagEntries(stateRef.current.actor),skills=learnedSkills(stateRef.current.actor),length=menu.tab===0?Math.max(1,entries.length):menu.tab===2?Math.max(1,skills.length):1;if(k==="arrowleft"||k==="a")setMenu({tab:(menu.tab+2)%3,index:0});else if(k==="arrowright"||k==="d"||k==="tab")setMenu({tab:(menu.tab+1)%3,index:0});else if(k==="arrowup"||k==="w")setMenu({...menu,index:(menu.index+length-1)%length});else if(k==="arrowdown"||k==="s")setMenu({...menu,index:(menu.index+1)%length});else if(confirm&&menu.tab===0)activateBagEntry(entries[menu.index]);else if(confirm&&menu.tab===2)activateSkill(skills[menu.index]?.id);else if((k==="c"||k==="r")&&menu.tab===2)activateSkill(skills[menu.index]?.id,true);else if(cancel||k==="m"||k==="e")setMenu(null);return;}if(eventText&&(confirm||cancel)){setEventText("");return;}if(npcMenu){const opts=npcOptions(npcMenu.id,stateRef.current.actor);if(k==="arrowup"||k==="w")setNpcMenu({...npcMenu,index:(npcMenu.index+opts.length-1)%opts.length});else if(k==="arrowdown"||k==="s")setNpcMenu({...npcMenu,index:(npcMenu.index+1)%opts.length});else if(confirm)chooseNpc(npcMenu.id,opts[npcMenu.index]);else if(cancel)setNpcMenu(null);return;}if(shop){const list=shopGoods(shop.id);if(k==="arrowup"||k==="w")setShop({...shop,index:(shop.index+list.length-1)%list.length});else if(k==="arrowdown"||k==="s")setShop({...shop,index:(shop.index+1)%list.length});else if(confirm)buySelected();else if(cancel)setShop(null);return;}if(study){const list=studyOptions(study.id);if(k==="arrowup"||k==="w")setStudy({...study,index:(study.index+list.length-1)%list.length});else if(k==="arrowdown"||k==="s")setStudy({...study,index:(study.index+1)%list.length});else if(confirm)studySelected();else if(cancel)setStudy(null);return;}if(confirm)interact();else if(k==="f")save();else if(["m","e","tab"].includes(k))setMenu({tab:0,index:0});else if(cancel)location.href="/";},up=(e:KeyboardEvent)=>{keys.current.delete(e.key.toLowerCase());delete held.current[e.key.toLowerCase()];};addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);};},[battle,buySelected,chooseNpc,eventText,fight,interact,leaveBattle,menu,npcMenu,save,shop,study,studySelected,activateBagEntry,activateSkill]);
 useEffect(()=>{const id=setInterval(()=>{const now=Date.now(),moves:Array<[string[],number,number]>=[[["w","arrowup"],0,-1],[["s","arrowdown"],0,1],[["a","arrowleft"],-1,0],[["d","arrowright"],1,0]];for(const [list,dx,dy]of moves){const k=list.find(v=>keys.current.has(v));if(k&&(!held.current[k]||now-held.current[k]>120)){held.current[k]=now;move(dx,dy);break;}}},30);return()=>clearInterval(id);},[move]);
 useEffect(()=>{let raf=0;const frame=()=>{const ctx=canvas.current?.getContext("2d");if(ctx)draw(ctx,stateRef.current.position);raf=requestAnimationFrame(frame);};frame();return()=>cancelAnimationFrame(raf);},[]);
 const exportJson=()=>{save();const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(stateRef.current,null,2)],{type:"application/json"}));a.download="英雄坛说-原版世界.json";a.click();URL.revokeObjectURL(a.href);};
 const importJson=async(f?:File)=>{if(!f)return;try{const x=JSON.parse(await f.text());if(x.format!=="rmxp-hero-original-world-save"||!getOriginalMap(x.position.mapId))throw 0;sync(normalize(x));setNotice("JSON 读取成功");}catch{setNotice("存档格式无效");}};
 const map=getOriginalMap(state.position.mapId);
 return <main className="world-shell"><header><Link href="/">← 云游志</Link><div><b>原版世界</b><span>69 MAP DATA RUNTIME</span></div><button onClick={save}>保存 <kbd>F</kbd></button></header><section className="world-frame"><canvas ref={canvas} width={W} height={H}/>{eventText&&<button className="world-dialog" onClick={()=>setEventText("")}>{eventText.split("\n").map((line,i)=><span key={i}>{line||" "}</span>)}<i>▼</i></button>}{npcMenu&&<Choice title={String(npcRecord(npcMenu.id).name)} items={npcOptions(npcMenu.id,state.actor).map(n=>npcOptionLabel[n])} index={npcMenu.index} choose={i=>chooseNpc(npcMenu.id,npcOptions(npcMenu.id,state.actor)[i])}/>} {shop&&<Choice title={`${npcRecord(shop.id).name} · ${state.actor.gold}两`} items={shopGoods(shop.id).map(g=>`${g.name} · ${g.price}两`)} index={shop.index} choose={i=>{setShop({...shop,index:i});buyAt(shop.id,i)}}/>} {study&&<Choice title="请教何种功夫" items={studyOptions(study.id).map(g=>`${g.name} · 上限${g.maxLevel}`)} index={study.index} choose={i=>{setStudy({...study,index:i});studyAt(study.id,i)}}/>}{battle&&<BattleView battle={battle} hp={state.actor.hp} maxHp={state.actor.maxHp} fight={fight} leave={leaveBattle}/>} {menu&&<GameMenu actor={state.actor} menu={menu} setMenu={setMenu} activate={activateBagEntry} activateKf={activateSkill}/>}</section><aside><div><small>当前位置</small><b>{map.name}</b><em>Map {map.id} · {map.width}×{map.height}</em></div><div><small>气血 / 内力</small><b>{state.actor.hp} / {state.actor.fp}</b></div><div><small>银两 / 潜能</small><b>{state.actor.gold} / {state.actor.potential}</b></div><p>{notice}</p><nav><button onClick={()=>setMenu({tab:0,index:0})}>行囊 <kbd>M</kbd></button><button onClick={exportJson}>下载 JSON</button><button onClick={()=>file.current?.click()}>读取 JSON</button></nav></aside><footer>移动 <kbd>WASD</kbd><kbd>方向键</kbd> · 互动 <kbd>Z</kbd><kbd>Enter</kbd> · 菜单 <kbd>M</kbd><kbd>Tab</kbd> · 返回 <kbd>Esc</kbd></footer><input hidden ref={file} type="file" accept=".json,application/json" onChange={e=>void importJson(e.target.files?.[0])}/></main>;
}

function Choice({title,items,index,choose}:{title:string;items:string[];index:number;choose:(index:number)=>void}){return <div className="world-choice"><b>{title}</b>{items.map((item,i)=><button className={i===index?"active":""} onClick={()=>choose(i)} key={`${item}-${i}`}><span>{item}</span>{i===index&&<i>◆</i>}</button>)}<small>W/S 选择 · Z 确认 · X 返回</small></div>}
function BattleView({battle,hp,maxHp,fight,leave}:{battle:OriginalBattle;hp:number;maxHp:number;fight:()=>void;leave:()=>void}){return <div className="battle"><div className="battle-stage"><div className="fighter hero"><i/><span>少侠</span></div><b>切磋 · 第 {battle.turn+1} 回合</b><div className="fighter enemy"><i/><span>{battle.enemyName}</span></div></div><div className="battle-bars"><label>你 <meter min="0" max={maxHp} value={hp}/><em>{hp}/{maxHp}</em></label><label>{battle.enemyName} <meter min="0" max={battle.enemyMaxHp} value={battle.enemyHp}/><em>{battle.enemyHp}/{battle.enemyMaxHp}</em></label></div><div className="battle-log">{battle.log.map((line,i)=><p key={`${i}-${line}`}>{line}</p>)}</div><nav><button onClick={battle.finished?leave:fight}>{battle.finished?"结束切磋":"普通攻击"} <kbd>Z</kbd></button><button onClick={leave}>退出 <kbd>X</kbd></button></nav></div>}
function GameMenu({actor,menu,setMenu,activate,activateKf}:{actor:SceneActorState;menu:{tab:number;index:number};setMenu:(value:{tab:number;index:number}|null)=>void;activate:(entry?:BagEntry)=>void;activateKf:(id?:number,parry?:boolean)=>void}){const tabs=["行囊","状态","功夫"],entries=bagEntries(actor),stats=derivedStats(actor);return <div className="game-menu"><nav>{tabs.map((tab,i)=><button key={tab} className={menu.tab===i?"active":""} onClick={()=>setMenu({tab:i,index:0})}>{tab}</button>)}</nav>{menu.tab===0?<section className="bag-list">{entries.length?entries.map((entry,i)=><button key={entry.key} className={menu.index===i?"active":""} onMouseEnter={()=>setMenu({tab:0,index:i})} onClick={()=>activate(entry)}><i className={`item-pixel kind-${entry.kind}`}/><span><b>{entry.name}{entry.equipped?"〔装备中〕":""}</b><small>{entry.description}</small></span><em>×{entry.amount}</em></button>):<p>行囊空空如也。</p>}</section>:menu.tab===1?<section className="status-grid"><b>江湖少侠 · {actor.age} 岁</b><span>气血 {actor.hp}/{actor.maxHp}</span><span>内力 {actor.fp}/{actor.maxFp}</span><span>膂力 {stats.str}</span><span>敏捷 {stats.agi}</span><span>悟性 {stats.int}</span><span>根骨 {stats.bon}</span><span>攻击 {stats.atk}</span><span>防御 {stats.pdef}</span><span>饱食 {actor.food}/{maxFood(actor)}</span><span>饮水 {actor.water}/{maxWater(actor)}</span><span>经验 {actor.exp}</span><span>潜能 {actor.potential}</span></section>:<SkillRows actor={actor} index={menu.index} setMenu={setMenu} activate={activateKf}/>}<footer>A/D 或 Tab 切页 · W/S 选择 · Z 装配 · C/R 设为招架 · X 关闭</footer></div>}
function SkillRows({actor,index,setMenu,activate}:{actor:SceneActorState;index:number;setMenu:(value:{tab:number;index:number})=>void;activate:(id?:number,parry?:boolean)=>void}){const skills=learnedSkills(actor);return <section className="skill-list">{skills.length?skills.map((skill,i)=><button className={index===i?"active":""} key={skill.id} onMouseEnter={()=>setMenu({tab:2,index:i})} onClick={()=>activate(skill.id)}><b>{skill.name}{skill.equipped?"〔运用〕":""}{skill.parrying?"〔招架〕":""}</b><span>{skill.level} 级</span><em>{skill.points} 点</em></button>):<p>尚未学会任何功夫，可向江湖人物拜师请教。</p>}</section>}

function draw(ctx:CanvasRenderingContext2D,pos:WorldPosition){const map=getOriginalMap(pos.mapId),ox=Math.floor(W/2/T),oy=Math.floor(H/2/T),sx=Math.max(0,Math.min(map.width-20,pos.x-ox)),sy=Math.max(0,Math.min(map.height-15,pos.y-oy));ctx.fillStyle="#0c1410";ctx.fillRect(0,0,W,H);for(let y=0;y<15;y++)for(let x=0;x<20;x++){const mx=sx+x,my=sy+y;if(mx>=map.width||my>=map.height)continue;drawTile(ctx,x*T,y*T,tileAt(map,mx,my,0),0);drawTile(ctx,x*T,y*T,tileAt(map,mx,my,1),1);drawTile(ctx,x*T,y*T,tileAt(map,mx,my,2),2);}for(const e of map.events){if(e.x<sx||e.y<sy||e.x>=sx+20||e.y>=sy+15)continue;const page=activePage(e),g=page.graphic||{},name=String(g.character_name||"");if(name)drawActor(ctx,(e.x-sx)*T+16,(e.y-sy)*T+23,hash(e.name),false);else if(page.commands.some(c=>c.code===201)){ctx.fillStyle="rgba(210,177,92,.65)";ctx.fillRect((e.x-sx)*T+12,(e.y-sy)*T+12,8,8);}}drawActor(ctx,(pos.x-sx)*T+16,(pos.y-sy)*T+23,"#dce8ec",true);ctx.fillStyle="rgba(5,10,7,.75)";ctx.fillRect(0,0,W,30);ctx.fillStyle="#eadcae";ctx.font="bold 15px serif";ctx.textAlign="left";ctx.fillText(map.name,14,20);ctx.textAlign="right";ctx.font="10px monospace";ctx.fillStyle="#9aaa9e";ctx.fillText(`MAP ${map.id}  ${pos.x},${pos.y}`,W-14,19);}
function drawTile(ctx:CanvasRenderingContext2D,x:number,y:number,id:number,layer:number){if(!id)return;const h=(id*47)%360;if(layer===0){ctx.fillStyle=`hsl(${80+(id%35)} 22% ${24+(id%5)*3}%)`;ctx.fillRect(x,y,T,T);ctx.fillStyle="rgba(255,255,255,.035)";ctx.fillRect(x+(id*7)%25,y+(id*11)%25,3,3);}else{ctx.fillStyle=`hsl(${h} ${28+layer*8}% ${31+layer*7}%)`;const kind=id%7;if(kind<2){ctx.fillRect(x+3,y+4,T-6,T-7);ctx.fillStyle="rgba(15,18,15,.32)";ctx.fillRect(x+3,y+22,T-6,7);}else if(kind<4){ctx.fillRect(x+13,y+3,6,27);ctx.fillRect(x+7,y+5,18,12);}else{ctx.fillRect(x+4,y+10,24,18);ctx.fillStyle="rgba(240,220,170,.15)";ctx.fillRect(x+7,y+13,18,3);}}}
function drawActor(ctx:CanvasRenderingContext2D,x:number,y:number,color:string,hero:boolean){ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(x-9,y+5,18,4);ctx.fillStyle="#26221d";ctx.fillRect(x-7,y-13,14,8);ctx.fillStyle="#dfb78d";ctx.fillRect(x-5,y-15,10,9);ctx.fillStyle=color;ctx.fillRect(x-8,y-7,16,14);ctx.fillStyle=hero?"#657f97":"#40362e";ctx.fillRect(x-8,y+7,6,7);ctx.fillRect(x+2,y+7,6,7);}
function hash(text:string){let n=0;for(const c of text)n=(n*31+c.charCodeAt(0))%360;return `hsl(${n} 45% 58%)`;}
