"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { activePage, getOriginalMap, originalMaps, originalStart, passable, tileAt, triggerEvent, type WorldPosition } from "../game-core/original-world";
import { applySceneResolution, resolveSceneEvent, type SceneActorState } from "../game-core/scene-event";
import { selectSceneEvent } from "../game-core/rmxp-events";
import "./world.css";

const W=640,H=480,T=32;
type WorldSave={format:"rmxp-hero-original-world-save";version:1;savedAt:string;position:WorldPosition;flags:Record<string,boolean>;variables:Record<string,number>;actor:SceneActorState};
const newActor=():SceneActorState=>({inventory:{},gold:0,hp:100,maxHp:100,fp:50,maxFp:50,food:100,water:100,exp:0,potential:0,morals:0,tanId:0});
const fresh=():WorldSave=>({format:"rmxp-hero-original-world-save",version:1,savedAt:new Date().toISOString(),position:{...originalStart},flags:{},variables:{},actor:newActor()});
const normalize=(value:WorldSave):WorldSave=>({...value,actor:value.actor||newActor(),flags:value.flags||{},variables:value.variables||{}});
const loadSave=():WorldSave=>{if(typeof window==="undefined")return fresh();try{const raw=localStorage.getItem("rmxp-original-world-v1");return raw?normalize(JSON.parse(raw)):fresh();}catch{return fresh();}};

export default function OriginalWorld(){
 const [state,setState]=useState<WorldSave>(loadSave),[notice,setNotice]=useState("原版地图数据已载入"),[eventText,setEventText]=useState("");
 const canvas=useRef<HTMLCanvasElement>(null), file=useRef<HTMLInputElement>(null), stateRef=useRef<WorldSave>(state), keys=useRef(new Set<string>()),held=useRef<Record<string,number>>({});
 const sync=useCallback((next:WorldSave)=>{stateRef.current=next;setState(structuredClone(next));},[]);
 const save=useCallback(()=>{const next={...stateRef.current,savedAt:new Date().toISOString()};sync(next);localStorage.setItem("rmxp-original-world-v1",JSON.stringify(next));setNotice("原版世界进度已保存");},[sync]);
 const runAt=useCallback((x:number,y:number,automatic=false)=>{const s=stateRef.current,map=getOriginalMap(s.position.mapId),hook=triggerEvent(map,x,y);if(!hook)return false;const {result,event,page}=hook;if(result.transfer){const next=structuredClone(s);next.position={mapId:result.transfer.mapId,x:result.transfer.x,y:result.transfer.y,direction:result.transfer.direction||s.position.direction};sync(next);setNotice(`抵达 · ${getOriginalMap(next.position.mapId).name}`);return true;}const sceneCall=selectSceneEvent(result.source,{inventory:s.actor.inventory,tanId:s.actor.tanId,freeWork:s.variables.freeWork||0,canGetItem:true,canGetCaihua:true});if(sceneCall&&!automatic){const next=structuredClone(s),resolution=resolveSceneEvent(sceneCall,next.actor,event.id+s.position.mapId);applySceneResolution(next.actor,resolution);if(resolution.transfer)next.position={...resolution.transfer,direction:next.position.direction};sync(next);setEventText(`${event.name||"地图事件"}\n${resolution.lines.join("\n")}`);setNotice(`原版事件 · ${resolution.tag}`);return true;}if(!automatic&&result.source&&!sceneCall){setNotice("尚未满足该事件的原版触发条件");return true;}return page.trigger>0;},[sync]);
 const move=useCallback((dx:number,dy:number)=>{if(eventText)return;const s=structuredClone(stateRef.current),map=getOriginalMap(s.position.mapId);const direction=dx<0?4:dx>0?6:dy<0?8:2,nx=s.position.x+dx,ny=s.position.y+dy;s.position.direction=direction;if(!passable(map,nx,ny,direction)){sync(s);return;}const blocking=map.events.find(e=>e.x===nx&&e.y===ny&&String(activePage(e).graphic?.character_name||"")&&!activePage(e).through);if(!blocking){s.position.x=nx;s.position.y=ny;sync(s);runAt(nx,ny,true);}else sync(s);},[eventText,runAt,sync]);
 const interact=useCallback(()=>{const p=stateRef.current.position,d=p.direction===2?[0,1]:p.direction===4?[-1,0]:p.direction===6?[1,0]:[0,-1];if(!runAt(p.x+d[0],p.y+d[1]))setNotice("这里没有可以触发的事件");},[runAt]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright"," "].includes(k))e.preventDefault();keys.current.add(k);if(eventText&&["z","enter"," ","x","escape"].includes(k)){setEventText("");return;}if(["z","enter"," "].includes(k))interact();else if(k==="f")save();else if(k==="escape"||k==="x")location.href="/";},up=(e:KeyboardEvent)=>{keys.current.delete(e.key.toLowerCase());delete held.current[e.key.toLowerCase()];};addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up);};},[eventText,interact,save]);
 useEffect(()=>{const id=setInterval(()=>{const now=Date.now(),moves:Array<[string[],number,number]>=[[["w","arrowup"],0,-1],[["s","arrowdown"],0,1],[["a","arrowleft"],-1,0],[["d","arrowright"],1,0]];for(const [list,dx,dy]of moves){const k=list.find(v=>keys.current.has(v));if(k&&(!held.current[k]||now-held.current[k]>120)){held.current[k]=now;move(dx,dy);break;}}},30);return()=>clearInterval(id);},[move]);
 useEffect(()=>{let raf=0;const frame=()=>{const ctx=canvas.current?.getContext("2d");if(ctx)draw(ctx,stateRef.current.position);raf=requestAnimationFrame(frame);};frame();return()=>cancelAnimationFrame(raf);},[]);
 const exportJson=()=>{save();const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(stateRef.current,null,2)],{type:"application/json"}));a.download="英雄坛说-原版世界.json";a.click();URL.revokeObjectURL(a.href);};
 const importJson=async(f?:File)=>{if(!f)return;try{const x=JSON.parse(await f.text());if(x.format!=="rmxp-hero-original-world-save"||!getOriginalMap(x.position.mapId))throw 0;sync(normalize(x));setNotice("JSON 读取成功");}catch{setNotice("存档格式无效");}};
 const map=getOriginalMap(state.position.mapId);
 return <main className="world-shell"><header><Link href="/">← 云游志</Link><div><b>原版世界</b><span>69 MAP DATA RUNTIME</span></div><button onClick={save}>保存 <kbd>F</kbd></button></header><section className="world-frame"><canvas ref={canvas} width={W} height={H}/>{eventText&&<button className="world-dialog" onClick={()=>setEventText("")}>{eventText.split("\n").map((line,i)=><span key={i}>{line||" "}</span>)}<i>▼</i></button>}</section><aside><div><small>当前位置</small><b>{map.name}</b><em>Map {map.id} · {map.width}×{map.height}</em></div><div><small>气血 / 内力</small><b>{state.actor.hp} / {state.actor.fp}</b></div><div><small>原版地图</small><b>{originalMaps.length} / 69</b></div><p>{notice}</p><nav><button onClick={exportJson}>下载 JSON</button><button onClick={()=>file.current?.click()}>读取 JSON</button></nav></aside><footer>移动 <kbd>WASD</kbd><kbd>方向键</kbd> · 互动 <kbd>Z</kbd><kbd>Enter</kbd> · 返回 <kbd>Esc</kbd></footer><input hidden ref={file} type="file" accept=".json,application/json" onChange={e=>void importJson(e.target.files?.[0])}/></main>;
}

function draw(ctx:CanvasRenderingContext2D,pos:WorldPosition){const map=getOriginalMap(pos.mapId),ox=Math.floor(W/2/T),oy=Math.floor(H/2/T),sx=Math.max(0,Math.min(map.width-20,pos.x-ox)),sy=Math.max(0,Math.min(map.height-15,pos.y-oy));ctx.fillStyle="#0c1410";ctx.fillRect(0,0,W,H);for(let y=0;y<15;y++)for(let x=0;x<20;x++){const mx=sx+x,my=sy+y;if(mx>=map.width||my>=map.height)continue;drawTile(ctx,x*T,y*T,tileAt(map,mx,my,0),0);drawTile(ctx,x*T,y*T,tileAt(map,mx,my,1),1);drawTile(ctx,x*T,y*T,tileAt(map,mx,my,2),2);}for(const e of map.events){if(e.x<sx||e.y<sy||e.x>=sx+20||e.y>=sy+15)continue;const page=activePage(e),g=page.graphic||{},name=String(g.character_name||"");if(name)drawActor(ctx,(e.x-sx)*T+16,(e.y-sy)*T+23,hash(e.name),false);else if(page.commands.some(c=>c.code===201)){ctx.fillStyle="rgba(210,177,92,.65)";ctx.fillRect((e.x-sx)*T+12,(e.y-sy)*T+12,8,8);}}drawActor(ctx,(pos.x-sx)*T+16,(pos.y-sy)*T+23,"#dce8ec",true);ctx.fillStyle="rgba(5,10,7,.75)";ctx.fillRect(0,0,W,30);ctx.fillStyle="#eadcae";ctx.font="bold 15px serif";ctx.textAlign="left";ctx.fillText(map.name,14,20);ctx.textAlign="right";ctx.font="10px monospace";ctx.fillStyle="#9aaa9e";ctx.fillText(`MAP ${map.id}  ${pos.x},${pos.y}`,W-14,19);}
function drawTile(ctx:CanvasRenderingContext2D,x:number,y:number,id:number,layer:number){if(!id)return;const h=(id*47)%360;if(layer===0){ctx.fillStyle=`hsl(${80+(id%35)} 22% ${24+(id%5)*3}%)`;ctx.fillRect(x,y,T,T);ctx.fillStyle="rgba(255,255,255,.035)";ctx.fillRect(x+(id*7)%25,y+(id*11)%25,3,3);}else{ctx.fillStyle=`hsl(${h} ${28+layer*8}% ${31+layer*7}%)`;const kind=id%7;if(kind<2){ctx.fillRect(x+3,y+4,T-6,T-7);ctx.fillStyle="rgba(15,18,15,.32)";ctx.fillRect(x+3,y+22,T-6,7);}else if(kind<4){ctx.fillRect(x+13,y+3,6,27);ctx.fillRect(x+7,y+5,18,12);}else{ctx.fillRect(x+4,y+10,24,18);ctx.fillStyle="rgba(240,220,170,.15)";ctx.fillRect(x+7,y+13,18,3);}}}
function drawActor(ctx:CanvasRenderingContext2D,x:number,y:number,color:string,hero:boolean){ctx.fillStyle="rgba(0,0,0,.25)";ctx.fillRect(x-9,y+5,18,4);ctx.fillStyle="#26221d";ctx.fillRect(x-7,y-13,14,8);ctx.fillStyle="#dfb78d";ctx.fillRect(x-5,y-15,10,9);ctx.fillStyle=color;ctx.fillRect(x-8,y-7,16,14);ctx.fillStyle=hero?"#657f97":"#40362e";ctx.fillRect(x-8,y+7,6,7);ctx.fillRect(x+2,y+7,6,7);}
function hash(text:string){let n=0;for(const c of text)n=(n*31+c.charCodeAt(0))%360;return `hsl(${n} 45% 58%)`;}
