import { originalTables, type OriginalRecord } from "./original-data";
import type { SceneActorState } from "./scene-event";

export type BagEntry={key:string;kind:1|2|3;id:number;amount:number;name:string;description:string;equipped:boolean};
const pair=(value:unknown):[number,number]=>Array.isArray(value)?[Number(value[0]||0),Number(value[1]||0)]:[0,0];
const table=(kind:number)=>kind===1?originalTables.items:kind===2?originalTables.weapons:originalTables.armors;
const add=(base:number,value:unknown,percentBase:number)=>{const [mode,amount]=pair(value);return base+(mode===1?Math.floor(percentBase*amount/100):amount);};
export const maxFood=(actor:SceneActorState)=>(actor.baseStr+5)*15;
export const maxWater=(actor:SceneActorState)=>(actor.baseStr+4)*15;
export function fullHp(actor:SceneActorState){let value=100+Math.floor(actor.maxFp/4)+(Math.min(actor.age,29)-14)*20;if(actor.classId===3&&(actor.skills["27"]?.level||0)>=80&&actor.age>=20)value+=Math.floor((actor.skills["27"].level*actor.baseBon)/10);return value;}
export function bagEntries(actor:SceneActorState):BagEntry[]{return Object.entries(actor.inventory).flatMap(([key,amount])=>{const [kind,id]=key.split(":").map(Number),record=table(kind)[id];if(!record||amount<=0||kind<1||kind>3)return[];return[{key,kind:kind as 1|2|3,id,amount,name:String(record.name||id),description:String(record.description||""),equipped:kind===2?actor.weaponId===id:kind===3?actor.armorIds.includes(id):false}]});}
function record(entry:BagEntry):OriginalRecord{return table(entry.kind)[entry.id]||{};}
export function equipmentBonus(actor:SceneActorState,key:"add_str"|"add_agi"|"add_int"|"add_bon"|"add_atk"|"add_def"|"add_hit"|"add_eva"){let value=0;if(actor.weaponId)value+=Number(originalTables.weapons[actor.weaponId]?.[key]||0);for(const id of actor.armorIds)value+=Number(originalTables.armors[id]?.[key]||0);return Math.min(255,value);}
export function derivedStats(actor:SceneActorState){return {str:Math.min(255,actor.baseStr+Math.floor((actor.skills["2"]?.level||0)/10)+equipmentBonus(actor,"add_str")),agi:Math.min(255,actor.baseAgi+Math.floor((actor.skills["9"]?.level||0)/10)+equipmentBonus(actor,"add_agi")),int:Math.min(255,actor.baseInt+Math.floor((actor.skills["11"]?.level||0)/10)+equipmentBonus(actor,"add_int")),bon:Math.min(255,actor.baseBon+Math.floor((actor.skills["1"]?.level||0)/10)+equipmentBonus(actor,"add_bon")),atk:equipmentBonus(actor,"add_atk"),pdef:equipmentBonus(actor,"add_def"),hit:equipmentBonus(actor,"add_hit"),eva:equipmentBonus(actor,"add_eva")};}
export function activateEntry(actor:SceneActorState,entry:BagEntry){const item=record(entry);if(entry.kind===2){actor.weaponId=actor.weaponId===entry.id?0:entry.id;return {ok:true,text:actor.weaponId?`装备了${entry.name}。`:`卸下了${entry.name}。`};}if(entry.kind===3){const kind=Number(item.kind||0),old=actor.armorIds.find(id=>Number(originalTables.armors[id]?.kind||0)===kind);actor.armorIds=actor.armorIds.filter(id=>id!==old&&id!==entry.id);if(old!==entry.id)actor.armorIds.push(entry.id);return {ok:true,text:old===entry.id?`卸下了${entry.name}。`:`装备了${entry.name}。`};}if(item.is_book)return {ok:false,text:"书籍需要读书识字，并在请教界面研习。"};const occasion=Number(item.occasion||0);if(occasion!==0&&occasion!==2)return {ok:false,text:"此物只能在战斗中使用。"};const before=[actor.hp,actor.maxHp,actor.fp,actor.maxFp,actor.food,actor.water].join();actor.food=Math.min(maxFood(actor),add(actor.food,item.add_food,maxFood(actor)));actor.water=Math.min(maxWater(actor),add(actor.water,item.add_water,maxWater(actor)));actor.hp=Math.min(actor.maxHp,add(actor.hp,item.add_hp,fullHp(actor)));actor.maxHp=Math.min(fullHp(actor),add(actor.maxHp,item.add_mhp,fullHp(actor)));actor.fp=Math.min(actor.maxFp*2,add(actor.fp,item.add_fp,actor.maxFp));actor.maxFp=add(actor.maxFp,item.add_mfp,actor.maxFp);if(before===[actor.hp,actor.maxHp,actor.fp,actor.maxFp,actor.food,actor.water].join())return {ok:false,text:"你现在不需要使用此物。"};if(item.consumable!==false){actor.inventory[entry.key]--;if(actor.inventory[entry.key]<=0)delete actor.inventory[entry.key];}return {ok:true,text:`使用了${entry.name}。`};}
